name: pywim
channels:
- conda-forge
- defaults
dependencies:
- alabaster=0.7.10=py36_0
- asn1crypto=0.22.0=py36_0
- babel=2.3.4=py36_0
- blas=1.1=openblas
- bleach=1.5.0=py36_0
- ca-certificates=2017.4.17=0
- certifi=2017.4.17=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.2=py36_1
- coverage=4.4.1=py36_0
- cryptography=1.9=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.10=3
- decorator=4.1.2=py36_0
- docutils=0.13.1=py36_0
- entrypoints=0.2.3=py36_1
- expat=2.2.1=0
- flake8=3.3.0=py36_0
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- glib=2.51.4=0
- gmp=6.1.2=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- h5py=2.7.0=np113py36_1
- hdf5=1.8.18=0
- html5lib=0.9999999=py36_0
- icu=58.1=1
- idna=2.5=py36_0
- imagesize=0.7.1=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.9.5=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_contrib_core=0.3.1=py36_0
- jupyter_contrib_nbextensions=0.2.8=py36_1
- jupyter_core=4.3.0=py36_0
- jupyter_highlight_selected_word=0.0.11=py36_0
- jupyter_latex_envs=1.3.8.2=py36_1
- jupyter_nbextensions_configurator=0.2.5=py36_0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=0
- libsodium=1.0.10=0
- libxcb=1.12=1
- libxml2=2.9.4=4
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=np113py36_0
- mccabe=0.6.1=py36_0
- mistune=0.7.4=py36_0
- nbconvert=5.2.1=py36_1
- nbformat=4.3.0=py36_0
- ncurses=5.9=10
- notebook=5.0.0=py36_0
- numpy=1.13.1=py36_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pandas=0.20.3=py36_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- patsy=0.4.1=py36_0
- pcre=8.39=0
- peakutils=1.1.0=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.3=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.14=py36_0
- psutil=5.2.1=py36_0
- ptyprocess=0.5.2=py36_0
- pycodestyle=2.3.1=py36_0
- pycparser=2.18=py36_0
- pyflakes=1.5.0=py36_0
- pygments=2.2.0=py36_0
- pyopenssl=16.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pysocks=1.6.7=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_1
- pyzmq=16.0.2=py36_2
- qt=5.6.2=3
- qtconsole=4.3.0=py36_0
- readline=6.2=0
- requests=2.18.2=py36_0
- scikit-learn=0.18.2=np113py36_blas_openblas_200
- scipy=0.19.1=np113py36_blas_openblas_200
- setuptools=36.2.2=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- snowballstemmer=1.2.1=py36_0
- sphinx=1.6.3=py36_0
- sphinxcontrib-websupport=1.0.1=py36_0
- sqlalchemy=1.1.11=py36_0
- sqlite=3.13.0=1
- statsmodels=0.8.0=np113py36_0
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.19=1
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- typing=3.6.1=py36_0
- urllib3=1.21.1=py36_1
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- libgfortran=3.0.0=1
- llvmlite=0.19.0=py36_0
- numba=0.34.0=np113py36_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-contrib-core==0.3.1
  - jupyter-contrib-nbextensions==0.2.8
  - jupyter-core==4.3.0
  - jupyter-highlight-selected-word==0.0.11
  - jupyter-latex-envs==1.3.8.2
  - jupyter-nbextensions-configurator==0.2.5
  - prompt-toolkit==1.0.14

